# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d73c4ff522b25613c82b48ee8f880e693beca46280aa668725b240319fc61eee05c86eb8912661312f3c184f64df02bed7de48b42d30c13ac96264ea16848eb6

test:
  secret_key_base: 82133b261a7ef8865aee149884c51f0aca16dfb28db09c4c2be95c46dff948475f9116f700f4aed0ad90ea4ebcce0f7b279a2afc3d1dab6c3944dd7d93e59009

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
